// Package protocol provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package protocol

import (
	"time"
)

// Defines values for BuildAttribution.
const (
	Declared BuildAttribution = "declared"
	Verified BuildAttribution = "verified"
)

// Valid indicates whether the value is a known member of the BuildAttribution enum.
func (e BuildAttribution) Valid() bool {
	switch e {
	case Declared:
		return true
	case Verified:
		return true
	default:
		return false
	}
}

// Defines values for ChallengeStatus.
const (
	ChallengeStatusExpired  ChallengeStatus = "expired"
	ChallengeStatusLive     ChallengeStatus = "live"
	ChallengeStatusRedeemed ChallengeStatus = "redeemed"
	ChallengeStatusRevoked  ChallengeStatus = "revoked"
)

// Valid indicates whether the value is a known member of the ChallengeStatus enum.
func (e ChallengeStatus) Valid() bool {
	switch e {
	case ChallengeStatusExpired:
		return true
	case ChallengeStatusLive:
		return true
	case ChallengeStatusRedeemed:
		return true
	case ChallengeStatusRevoked:
		return true
	default:
		return false
	}
}

// Defines values for ChallengeIssuedStatus.
const (
	ChallengeIssuedStatusExpired  ChallengeIssuedStatus = "expired"
	ChallengeIssuedStatusLive     ChallengeIssuedStatus = "live"
	ChallengeIssuedStatusRedeemed ChallengeIssuedStatus = "redeemed"
	ChallengeIssuedStatusRevoked  ChallengeIssuedStatus = "revoked"
)

// Valid indicates whether the value is a known member of the ChallengeIssuedStatus enum.
func (e ChallengeIssuedStatus) Valid() bool {
	switch e {
	case ChallengeIssuedStatusExpired:
		return true
	case ChallengeIssuedStatusLive:
		return true
	case ChallengeIssuedStatusRedeemed:
		return true
	case ChallengeIssuedStatusRevoked:
		return true
	default:
		return false
	}
}

// Defines values for MemberWithUserRole.
const (
	MemberWithUserRoleAdmin  MemberWithUserRole = "admin"
	MemberWithUserRoleMember MemberWithUserRole = "member"
	MemberWithUserRoleOwner  MemberWithUserRole = "owner"
)

// Valid indicates whether the value is a known member of the MemberWithUserRole enum.
func (e MemberWithUserRole) Valid() bool {
	switch e {
	case MemberWithUserRoleAdmin:
		return true
	case MemberWithUserRoleMember:
		return true
	case MemberWithUserRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for MembershipRole.
const (
	MembershipRoleAdmin  MembershipRole = "admin"
	MembershipRoleMember MembershipRole = "member"
	MembershipRoleOwner  MembershipRole = "owner"
)

// Valid indicates whether the value is a known member of the MembershipRole enum.
func (e MembershipRole) Valid() bool {
	switch e {
	case MembershipRoleAdmin:
		return true
	case MembershipRoleMember:
		return true
	case MembershipRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for OrgWithRoleRole.
const (
	OrgWithRoleRoleAdmin  OrgWithRoleRole = "admin"
	OrgWithRoleRoleMember OrgWithRoleRole = "member"
	OrgWithRoleRoleOwner  OrgWithRoleRole = "owner"
)

// Valid indicates whether the value is a known member of the OrgWithRoleRole enum.
func (e OrgWithRoleRole) Valid() bool {
	switch e {
	case OrgWithRoleRoleAdmin:
		return true
	case OrgWithRoleRoleMember:
		return true
	case OrgWithRoleRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for Plan.
const (
	Enterprise Plan = "enterprise"
	Free       Plan = "free"
	Paid       Plan = "paid"
)

// Valid indicates whether the value is a known member of the Plan enum.
func (e Plan) Valid() bool {
	switch e {
	case Enterprise:
		return true
	case Free:
		return true
	case Paid:
		return true
	default:
		return false
	}
}

// Defines values for PolicyState.
const (
	PolicyStateLive    PolicyState = "live"
	PolicyStateRevoked PolicyState = "revoked"
)

// Valid indicates whether the value is a known member of the PolicyState enum.
func (e PolicyState) Valid() bool {
	switch e {
	case PolicyStateLive:
		return true
	case PolicyStateRevoked:
		return true
	default:
		return false
	}
}

// Defines values for PolicyWithRepositoryState.
const (
	PolicyWithRepositoryStateLive    PolicyWithRepositoryState = "live"
	PolicyWithRepositoryStateRevoked PolicyWithRepositoryState = "revoked"
)

// Valid indicates whether the value is a known member of the PolicyWithRepositoryState enum.
func (e PolicyWithRepositoryState) Valid() bool {
	switch e {
	case PolicyWithRepositoryStateLive:
		return true
	case PolicyWithRepositoryStateRevoked:
		return true
	default:
		return false
	}
}

// Defines values for Provider.
const (
	Github Provider = "github"
)

// Valid indicates whether the value is a known member of the Provider enum.
func (e Provider) Valid() bool {
	switch e {
	case Github:
		return true
	default:
		return false
	}
}

// Defines values for Visibility.
const (
	Internal Visibility = "internal"
	Private  Visibility = "private"
	Public   Visibility = "public"
)

// Valid indicates whether the value is a known member of the Visibility enum.
func (e Visibility) Valid() bool {
	switch e {
	case Internal:
		return true
	case Private:
		return true
	case Public:
		return true
	default:
		return false
	}
}

// Defines values for InviteMemberJSONBodyRole.
const (
	InviteMemberJSONBodyRoleAdmin  InviteMemberJSONBodyRole = "admin"
	InviteMemberJSONBodyRoleMember InviteMemberJSONBodyRole = "member"
)

// Valid indicates whether the value is a known member of the InviteMemberJSONBodyRole enum.
func (e InviteMemberJSONBodyRole) Valid() bool {
	switch e {
	case InviteMemberJSONBodyRoleAdmin:
		return true
	case InviteMemberJSONBodyRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for ChangeMemberRoleJSONBodyRole.
const (
	ChangeMemberRoleJSONBodyRoleAdmin  ChangeMemberRoleJSONBodyRole = "admin"
	ChangeMemberRoleJSONBodyRoleMember ChangeMemberRoleJSONBodyRole = "member"
	ChangeMemberRoleJSONBodyRoleOwner  ChangeMemberRoleJSONBodyRole = "owner"
)

// Valid indicates whether the value is a known member of the ChangeMemberRoleJSONBodyRole enum.
func (e ChangeMemberRoleJSONBodyRole) Valid() bool {
	switch e {
	case ChangeMemberRoleJSONBodyRoleAdmin:
		return true
	case ChangeMemberRoleJSONBodyRoleMember:
		return true
	case ChangeMemberRoleJSONBodyRoleOwner:
		return true
	default:
		return false
	}
}

// Build The authenticated disclosure tier — full metadata (spec §2.7).
type Build struct {
	// Attribution `verified`: registered by `registerBuild` with a workload OIDC token
	// confirming repository identity against the CI provider's own claims —
	// spec §2.2a/§4's full provenance chain. `declared`: registered by
	// `registerDeclaredBuild`, a human-authenticated write with
	// self-reported repository/ref/commit — org-attributed and carrying
	// exactly the trust level of the rest of this record's fields, not a
	// provenance claim. Callers that render this record MUST label the
	// tier rather than implying verification that didn't happen.
	Attribution BuildAttribution `json:"attribution"`

	// BuildInstanceId Opaque and server-issued. For a `verified` build, content-addressed
	// over the tuple documented on `registerBuild`; for a `declared` build,
	// random (there is no run_id/run_attempt to content-address over — spec
	// §2.5a's tuple only ever applied to the CI producer). Clients MUST
	// treat this as opaque and MUST NOT parse it either way.
	BuildInstanceId string    `json:"build_instance_id"`
	BuiltAt         time.Time `json:"built_at"`
	CommitAuthor    *string   `json:"commit_author,omitempty"`
	CommitCommitter *string   `json:"commit_committer,omitempty"`
	CommitSha       string    `json:"commit_sha"`

	// Metadata Free-form organization-defined fields (owning team, ticket reference,
	// environment label). Flat string-to-string by design (spec §2.2a): nesting
	// would destabilize the wire type under the compatibility window, hurt
	// queryability, and invite this field to become a blob store.
	//
	// **Always authenticated-tier only.** Customers place arbitrary content here,
	// and the two-tier disclosure model depends on knowing exactly what is public,
	// so these values never appear in the unauthenticated resolution page or its OG
	// tags. There is no per-key public opt-in in v1.
	//
	// Keys beginning `driftmapper.` are reserved and rejected, leaving room to
	// promote custom fields to first-class ones later without collision. The
	// reserved-prefix rule is enforced in server code rather than expressed in the
	// `pattern` below: the natural expression is a negative lookahead, which Go's
	// RE2 engine cannot compile, so encoding it here would produce a schema the
	// server cannot mechanically enforce.
	Metadata *BuildMetadata `json:"metadata,omitempty"`

	// Provider Present only when `attribution` is `verified` — see `repository_id`.
	Provider     *Provider `json:"provider,omitempty"`
	Ref          *string   `json:"ref,omitempty"`
	RegisteredAt time.Time `json:"registered_at"`

	// RepositoryId Provider's stable repository identifier. Internal identity is keyed on
	// this rather than `owner/name`, which changes on rename. Present only
	// when `attribution` is `verified` — a `declared` build has no linked
	// `repositories` row, only the self-reported `repository_name`/
	// `repository_path` below.
	RepositoryId   *string `json:"repository_id,omitempty"`
	RepositoryName string  `json:"repository_name"`

	// RepositoryPath Full `owner/name` path. Authenticated tier only.
	RepositoryPath *string `json:"repository_path,omitempty"`

	// ResolutionUrl Canonical resolution page for this build — the URL written into
	// `build-info.html`. Server-provided so the CLI never constructs it and
	// cannot drift from server routing.
	ResolutionUrl *string `json:"resolution_url,omitempty"`

	// RunAttempt A passthrough OIDC claim value (GitHub's `run_attempt` claim is itself a
	// string), never parsed or compared numerically server-side — only used as
	// one input to the content-address tuple (spec §2.5a). Typed as a string
	// rather than `integer` for that reason.
	RunAttempt   *string `json:"run_attempt,omitempty"`
	RunId        *string `json:"run_id,omitempty"`
	TriggerEvent *string `json:"trigger_event,omitempty"`

	// Visibility Present only when `attribution` is `verified` — see `repository_id`.
	Visibility *Visibility `json:"visibility,omitempty"`
	Workflow   *string     `json:"workflow,omitempty"`
}

// BuildAttribution `verified`: registered by `registerBuild` with a workload OIDC token
// confirming repository identity against the CI provider's own claims —
// spec §2.2a/§4's full provenance chain. `declared`: registered by
// `registerDeclaredBuild`, a human-authenticated write with
// self-reported repository/ref/commit — org-attributed and carrying
// exactly the trust level of the rest of this record's fields, not a
// provenance claim. Callers that render this record MUST label the
// tier rather than implying verification that didn't happen.
type BuildAttribution string

// BuildListPayload defines model for BuildListPayload.
type BuildListPayload struct {
	Items []Build  `json:"items"`
	Page  PageInfo `json:"page"`
}

// BuildListResponse defines model for BuildListResponse.
type BuildListResponse struct {
	Data BuildListPayload `json:"data"`
}

// BuildMetadata Free-form organization-defined fields (owning team, ticket reference,
// environment label). Flat string-to-string by design (spec §2.2a): nesting
// would destabilize the wire type under the compatibility window, hurt
// queryability, and invite this field to become a blob store.
//
// **Always authenticated-tier only.** Customers place arbitrary content here,
// and the two-tier disclosure model depends on knowing exactly what is public,
// so these values never appear in the unauthenticated resolution page or its OG
// tags. There is no per-key public opt-in in v1.
//
// Keys beginning `driftmapper.` are reserved and rejected, leaving room to
// promote custom fields to first-class ones later without collision. The
// reserved-prefix rule is enforced in server code rather than expressed in the
// `pattern` below: the natural expression is a negative lookahead, which Go's
// RE2 engine cannot compile, so encoding it here would produce a schema the
// server cannot mechanically enforce.
type BuildMetadata map[string]string

// BuildPublic The unauthenticated disclosure tier (spec §2.7). This is exactly what link
// unfurlers and logged-out visitors see on the resolution page: enough to make
// a preview useful and confirm the link is a real Driftmapper build link,
// and nothing more.
//
// Deliberately excludes committer, author, internal repository path, and all
// custom metadata. This tier matches the disclosure boundary teams already have
// with a plain public build-info file, so nothing that is public today becomes
// private and nothing private today becomes public.
type BuildPublic struct {
	BuildInstanceId string    `json:"build_instance_id"`
	BuiltAt         time.Time `json:"built_at"`

	// RepositoryName Short repository name only — never the full internal path.
	RepositoryName string `json:"repository_name"`
}

// BuildRegistration Shared by both `registerBuild` (workload OIDC) and `registerDeclaredBuild`
// (human session) — DRFT-129 inverts spec §2.2a's original "token-derived,
// never from the body" rule to "confirm, don't derive." The CLI now reads
// git directly and submits its own view of build identity on every
// registration, for both producers.
//
// On `registerBuild`, `repository` is optional (omitting it is still valid,
// for backward compatibility with CLI versions predating this field) but
// when present is *confirmed* against the workload OIDC token's verified
// repository claim and rejected with `claim_mismatch` on any difference —
// it is never trusted from the body alone on that path, and the stored
// build is still attributed to the claims-derived repository, not the
// submitted one. `ref` on that path is informational only; the token's own
// `ref` claim remains authoritative.
//
// On `registerDeclaredBuild` there is no token to confirm against:
// `repository` is required, self-reported, and is exactly what gets
// stored — see `Build.attribution`.
type BuildRegistration struct {
	BuiltAt time.Time `json:"built_at"`

	// CommitAuthor Normalized by the CLI from provider-specific build context.
	CommitAuthor    *string `json:"commit_author,omitempty"`
	CommitCommitter *string `json:"commit_committer,omitempty"`
	CommitSha       string  `json:"commit_sha"`

	// Metadata Free-form organization-defined fields (owning team, ticket reference,
	// environment label). Flat string-to-string by design (spec §2.2a): nesting
	// would destabilize the wire type under the compatibility window, hurt
	// queryability, and invite this field to become a blob store.
	//
	// **Always authenticated-tier only.** Customers place arbitrary content here,
	// and the two-tier disclosure model depends on knowing exactly what is public,
	// so these values never appear in the unauthenticated resolution page or its OG
	// tags. There is no per-key public opt-in in v1.
	//
	// Keys beginning `driftmapper.` are reserved and rejected, leaving room to
	// promote custom fields to first-class ones later without collision. The
	// reserved-prefix rule is enforced in server code rather than expressed in the
	// `pattern` below: the natural expression is a negative lookahead, which Go's
	// RE2 engine cannot compile, so encoding it here would produce a schema the
	// server cannot mechanically enforce.
	Metadata *BuildMetadata `json:"metadata,omitempty"`

	// Ref Git ref, e.g. `refs/heads/main`. Read directly from git by the CLI
	// (`internal/gitcontext`). Informational on `registerBuild`; the only
	// source of truth on `registerDeclaredBuild`.
	Ref *string `json:"ref,omitempty"`

	// Repository `owner/name`. See this schema's own description for how the two
	// registration operations treat this field differently.
	Repository *string `json:"repository,omitempty"`

	// TriggerEvent Normalized trigger, e.g. `push`, `pull_request`, `manual`.
	TriggerEvent *string `json:"trigger_event,omitempty"`
}

// BuildResponse defines model for BuildResponse.
type BuildResponse struct {
	// Data The authenticated disclosure tier — full metadata (spec §2.7).
	Data Build `json:"data"`
}

// Challenge defines model for Challenge.
type Challenge struct {
	// Attempts Failed redemption attempts against this challenge so far.
	Attempts  int       `json:"attempts"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
	Id        int64     `json:"id"`

	// MaxAttempts The cap `attempts` is counted against — past this, redemption
	// rejects the challenge outright regardless of `status`/`expires_at`.
	MaxAttempts int        `json:"max_attempts"`
	RedeemedAt  *time.Time `json:"redeemed_at,omitempty"`

	// Status Derived, not stored — see `model.Challenge.State()`. Does not
	// reflect the attempt cap: a challenge that has hit `max_attempts`
	// still reports `live` here until it also expires or is revoked
	// (redemption itself is what enforces the cap; this field alone
	// isn't sufficient to know whether a further redemption attempt
	// would succeed).
	Status ChallengeStatus `json:"status"`
}

// ChallengeStatus Derived, not stored — see `model.Challenge.State()`. Does not
// reflect the attempt cap: a challenge that has hit `max_attempts`
// still reports `live` here until it also expires or is revoked
// (redemption itself is what enforces the cap; this field alone
// isn't sufficient to know whether a further redemption attempt
// would succeed).
type ChallengeStatus string

// ChallengeIssued defines model for ChallengeIssued.
type ChallengeIssued struct {
	// Attempts Failed redemption attempts against this challenge so far.
	Attempts  int       `json:"attempts"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
	Id        int64     `json:"id"`

	// MaxAttempts The cap `attempts` is counted against — past this, redemption
	// rejects the challenge outright regardless of `status`/`expires_at`.
	MaxAttempts int        `json:"max_attempts"`
	RedeemedAt  *time.Time `json:"redeemed_at,omitempty"`

	// Status Derived, not stored — see `model.Challenge.State()`. Does not
	// reflect the attempt cap: a challenge that has hit `max_attempts`
	// still reports `live` here until it also expires or is revoked
	// (redemption itself is what enforces the cap; this field alone
	// isn't sufficient to know whether a further redemption attempt
	// would succeed).
	Status ChallengeIssuedStatus `json:"status"`

	// Value The raw, single-use challenge secret. Returned **only** by
	// `createChallenge`, and only on that one response — never
	// recoverable afterward, never present on `listChallenges`
	// rows. Paste it into CI as `DRIFTMAPPER_CHALLENGE` before
	// navigating away.
	Value string `json:"value"`
}

// ChallengeIssuedStatus Derived, not stored — see `model.Challenge.State()`. Does not
// reflect the attempt cap: a challenge that has hit `max_attempts`
// still reports `live` here until it also expires or is revoked
// (redemption itself is what enforces the cap; this field alone
// isn't sufficient to know whether a further redemption attempt
// would succeed).
type ChallengeIssuedStatus string

// ChallengeIssuedResponse defines model for ChallengeIssuedResponse.
type ChallengeIssuedResponse struct {
	Data ChallengeIssued `json:"data"`
}

// ChallengeListResponse defines model for ChallengeListResponse.
type ChallengeListResponse struct {
	Data []Challenge `json:"data"`
}

// ClaimMismatchDetails `error.details` shape when `error.code` is `claim_mismatch`: a signature-
// valid token whose claims did not satisfy the repository's authorization
// policy.
//
// The mismatched field is named explicitly rather than returning a generic
// authentication failure. This is the single most likely point of first-run
// abandonment — a case-sensitive workflow filename mismatch is a well-
// documented source of setup friction in comparable systems (spec §4.5) —
// and a specific error is cheap to produce and turns a dead end into a
// one-line fix.
type ClaimMismatchDetails struct {
	// Actual Value from the verified token. Safe to echo: the caller demonstrably
	// already holds this token.
	Actual string `json:"actual"`

	// Expected Value the policy requires.
	Expected string `json:"expected"`

	// MismatchedClaim e.g. `workflow`, `ref`, `environment`.
	MismatchedClaim string `json:"mismatched_claim"`
}

// Error The `error` half of the response envelope (see "Response envelope" above).
// Not RFC 9457 — a from-scratch shape matching what every `cmd/api` route
// actually emits (`internal/api/respond.go`'s `errorBody`).
type Error struct {
	// Code Stable, machine-readable identity of the error. Clients branch on this,
	// never on `message`, which may be reworded without a version bump.
	// Examples: `validation`, `unauthorized`, `forbidden`, `not_found`,
	// `unknown_field`, `claim_mismatch`, `policy_revoked`, `no_live_policy`,
	// `rate_limited`.
	Code string `json:"code"`

	// Details Structured, error-specific fields a client can act on programmatically,
	// shaped per `error.code`. Present only for errors that document a shape;
	// absent otherwise. Two currently do: `claim_mismatch` (see
	// `ClaimMismatchDetails`) and `rate_limited` (see `RateLimitDetails` —
	// emitted generically by the service-layer rate limiter, so it can appear
	// on any operation, not only the ones whose `429` is individually
	// documented above).
	//
	// Deliberately not a `oneOf` of the two: `details` is one field shared by
	// every error response, not a per-code branch point, and a new code may
	// add its own shape later without a version bump (this document's
	// additive-within-major rule).
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Human-readable, safe to display directly.
	Message string `json:"message"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	// Error The `error` half of the response envelope (see "Response envelope" above).
	// Not RFC 9457 — a from-scratch shape matching what every `cmd/api` route
	// actually emits (`internal/api/respond.go`'s `errorBody`).
	Error Error `json:"error"`
}

// Invite defines model for Invite.
type Invite struct {
	Email string `json:"email"`

	// ExpiresAt ISO-8601
	ExpiresAt string `json:"expires_at"`

	// Id Opaque WorkOS invitation id.
	Id             string `json:"id"`
	OrganizationId string `json:"organization_id"`
	State          string `json:"state"`
}

// InviteResponse defines model for InviteResponse.
type InviteResponse struct {
	Data Invite `json:"data"`
}

// MemberWithUser defines model for MemberWithUser.
type MemberWithUser struct {
	CreatedAt time.Time          `json:"created_at"`
	Email     string             `json:"email"`
	Id        int64              `json:"id"`
	OrgId     int64              `json:"org_id"`
	Role      MemberWithUserRole `json:"role"`
	UserId    int64              `json:"user_id"`
}

// MemberWithUserRole defines model for MemberWithUser.Role.
type MemberWithUserRole string

// Membership defines model for Membership.
type Membership struct {
	CreatedAt time.Time      `json:"created_at"`
	Id        int64          `json:"id"`
	OrgId     int64          `json:"org_id"`
	Role      MembershipRole `json:"role"`
	UserId    int64          `json:"user_id"`
}

// MembershipRole defines model for Membership.Role.
type MembershipRole string

// Org defines model for Org.
type Org struct {
	CreatedAt time.Time `json:"created_at"`
	Id        int64     `json:"id"`
	Name      string    `json:"name"`

	// Personal True for the user's auto-created personal org.
	Personal bool   `json:"personal"`
	Slug     string `json:"slug"`
}

// OrgListResponse defines model for OrgListResponse.
type OrgListResponse struct {
	Data []OrgWithRole `json:"data"`
}

// OrgMembersPayload defines model for OrgMembersPayload.
type OrgMembersPayload struct {
	Invites []Invite         `json:"invites"`
	Members []MemberWithUser `json:"members"`
}

// OrgMembersResponse defines model for OrgMembersResponse.
type OrgMembersResponse struct {
	Data OrgMembersPayload `json:"data"`
}

// OrgResponse defines model for OrgResponse.
type OrgResponse struct {
	Data Org `json:"data"`
}

// OrgWithRole defines model for OrgWithRole.
type OrgWithRole struct {
	CreatedAt time.Time `json:"created_at"`
	Id        int64     `json:"id"`
	Name      string    `json:"name"`

	// Personal True for the user's auto-created personal org.
	Personal bool `json:"personal"`

	// Role The caller's role in this organization.
	Role OrgWithRoleRole `json:"role"`
	Slug string          `json:"slug"`
}

// OrgWithRoleRole The caller's role in this organization.
type OrgWithRoleRole string

// Organization defines model for Organization.
type Organization struct {
	Name           string `json:"name"`
	OrganizationId string `json:"organization_id"`
	Plan           Plan   `json:"plan"`
	SsoEnforced    *bool  `json:"sso_enforced,omitempty"`
}

// OrganizationResponse defines model for OrganizationResponse.
type OrganizationResponse struct {
	Data Organization `json:"data"`
}

// PageInfo defines model for PageInfo.
type PageInfo struct {
	HasMore bool `json:"has_more"`

	// NextCursor Present only when `has_more` is true.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// Plan defines model for Plan.
type Plan string

// Policy defines model for Policy.
type Policy struct {
	BoundAt time.Time `json:"bound_at"`

	// Environment Deployment-environment constraint. Null means unconstrained; an
	// empty string is a real constraint meaning "must target no
	// environment" (spec §4.5).
	Environment *string `json:"environment,omitempty"`
	Id          int64   `json:"id"`

	// Ref Git ref constraint (e.g. `refs/heads/main`). Null means unconstrained.
	Ref       *string     `json:"ref,omitempty"`
	RevokedAt *time.Time  `json:"revoked_at,omitempty"`
	State     PolicyState `json:"state"`

	// Workflow Bare workflow-filename constraint (e.g. `ci.yml`). Null means
	// unconstrained — redemption's default policy leaves it unset.
	Workflow *string `json:"workflow,omitempty"`
}

// PolicyState defines model for Policy.State.
type PolicyState string

// PolicyListResponse defines model for PolicyListResponse.
type PolicyListResponse struct {
	Data []PolicyWithRepository `json:"data"`
}

// PolicyWithRepository defines model for PolicyWithRepository.
type PolicyWithRepository struct {
	BoundAt time.Time `json:"bound_at"`

	// Environment Deployment-environment constraint. Null means unconstrained; an
	// empty string is a real constraint meaning "must target no
	// environment" (spec §4.5).
	Environment *string `json:"environment,omitempty"`
	Id          int64   `json:"id"`

	// Provider CI provider identity. v1 supports GitHub Actions only; further providers are
	// additive registry entries and appear here as new enum members (spec §4.4).
	// Clients MUST tolerate unknown values in responses.
	//
	// `github` is the issuer registry entry name (`internal/oidc.GitHubActionsProviderName`
	// server-side), not a literal "GitHub Actions" spelling — matches what every
	// `provider`/`claims.Issuer` value on the wire actually contains.
	Provider Provider `json:"provider"`

	// Ref Git ref constraint (e.g. `refs/heads/main`). Null means unconstrained.
	Ref          *string `json:"ref,omitempty"`
	RepositoryId string  `json:"repository_id"`

	// RepositoryPath `owner/name` at time of binding.
	RepositoryPath string                    `json:"repository_path"`
	RevokedAt      *time.Time                `json:"revoked_at,omitempty"`
	State          PolicyWithRepositoryState `json:"state"`

	// Workflow Bare workflow-filename constraint (e.g. `ci.yml`). Null means
	// unconstrained — redemption's default policy leaves it unset.
	Workflow *string `json:"workflow,omitempty"`
}

// PolicyWithRepositoryState defines model for PolicyWithRepository.State.
type PolicyWithRepositoryState string

// Provider CI provider identity. v1 supports GitHub Actions only; further providers are
// additive registry entries and appear here as new enum members (spec §4.4).
// Clients MUST tolerate unknown values in responses.
//
// `github` is the issuer registry entry name (`internal/oidc.GitHubActionsProviderName`
// server-side), not a literal "GitHub Actions" spelling — matches what every
// `provider`/`claims.Issuer` value on the wire actually contains.
type Provider string

// RateLimitDetails `error.details` shape when `error.code` is `rate_limited`. Emitted
// generically from the service layer (`internal/api/respond.go`'s
// `respondServiceError`, matched via `errors.As` against
// `service.RateLimitError`) rather than by one specific handler, so this
// can appear on any operation whose 429 response isn't individually
// documented with its own details shape — see e.g. `redeemChallenge` and
// `createChallenge` above, which each have their own distinct limit but
// share this one details shape.
type RateLimitDetails struct {
	// Limit The quota that was exceeded.
	Limit int `json:"limit"`

	// RetryAfterSeconds Matches the response's `Retry-After` header (RFC 9110 §10.2.3) — a
	// fixed-window counter's true reset could be sooner than a full
	// window, but that's a safe under-promise, never an over-promise a
	// client would retry too early against.
	RetryAfterSeconds int `json:"retry_after_seconds"`

	// Scope Identifies which quota was exceeded (e.g. which limiter matched) —
	// distinguishes this rate limit from any other the same account may
	// be subject to elsewhere.
	Scope string `json:"scope"`
}

// Repository defines model for Repository.
type Repository struct {
	LatestBuildInstanceId *string   `json:"latest_build_instance_id,omitempty"`
	LinkedAt              time.Time `json:"linked_at"`

	// Path `owner/name` at time of last build.
	Path string `json:"path"`

	// Provider CI provider identity. v1 supports GitHub Actions only; further providers are
	// additive registry entries and appear here as new enum members (spec §4.4).
	// Clients MUST tolerate unknown values in responses.
	//
	// `github` is the issuer registry entry name (`internal/oidc.GitHubActionsProviderName`
	// server-side), not a literal "GitHub Actions" spelling — matches what every
	// `provider`/`claims.Issuer` value on the wire actually contains.
	Provider     Provider `json:"provider"`
	RepositoryId string   `json:"repository_id"`

	// Visibility Derived from the `repository_visibility` OIDC claim, never client-supplied.
	// This is what gates the Free tier's public-repo allowance (spec §6A), so it is
	// enforced from the signed token with no VCS API call.
	Visibility Visibility `json:"visibility"`
}

// RepositoryAuthorization Confirmation that a challenge was redeemed and the repository is now
// bound — not a full policy record (constraints, timestamps; see
// `Policy`/`listPolicies`, the dashboard-tier policy-management
// operations, DRFT-63).
type RepositoryAuthorization struct {
	OrganizationId string `json:"organization_id"`

	// RepositoryId Provider's stable repository identifier, same identity space as `Build.repository_id`.
	RepositoryId string `json:"repository_id"`
}

// RepositoryAuthorizationResponse defines model for RepositoryAuthorizationResponse.
type RepositoryAuthorizationResponse struct {
	// Data Confirmation that a challenge was redeemed and the repository is now
	// bound — not a full policy record (constraints, timestamps; see
	// `Policy`/`listPolicies`, the dashboard-tier policy-management
	// operations, DRFT-63).
	Data RepositoryAuthorization `json:"data"`
}

// RepositoryAuthorizeRequest Repository identity is never accepted here — it comes only from the
// verified workload OIDC token (spec §4.5), same rule as
// `BuildRegistration`'s token-derived fields.
type RepositoryAuthorizeRequest struct {
	// Challenge The single-use value issued by `POST /v1/orgs/{slug}/challenges`.
	// Bearer secret — never logged, never written to disk by a
	// conforming client.
	Challenge string `json:"challenge"`
}

// RepositoryListPayload defines model for RepositoryListPayload.
type RepositoryListPayload struct {
	Items []Repository `json:"items"`
	Page  PageInfo     `json:"page"`
}

// RepositoryListResponse defines model for RepositoryListResponse.
type RepositoryListResponse struct {
	Data RepositoryListPayload `json:"data"`
}

// UpdatePolicyRequest Full-replace on the three constrainable dimensions: omit a property
// or send it null to leave/set that dimension unconstrained, resubmit
// the current value for anything you're not changing. No
// `repository_id`/`issuer`/`org_id` property exists here — rebinding a
// policy to a different repository or org is a new challenge (DRFT-59/
// 62), never an edit.
type UpdatePolicyRequest struct {
	Environment *string `json:"environment,omitempty"`
	Ref         *string `json:"ref,omitempty"`
	Workflow    *string `json:"workflow,omitempty"`
}

// User This system's own local mirror of the signed-in WorkOS user.
type User struct {
	CreatedAt          time.Time `json:"created_at"`
	Email              string    `json:"email"`
	EmailNotifications bool      `json:"email_notifications"`
	EmailVerified      bool      `json:"email_verified"`
	Id                 int64     `json:"id"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	// Data This system's own local mirror of the signed-in WorkOS user.
	Data User `json:"data"`
}

// Visibility Derived from the `repository_visibility` OIDC claim, never client-supplied.
// This is what gates the Free tier's public-repo allowance (spec §6A), so it is
// enforced from the signed token with no VCS API call.
type Visibility string

// BuildInstanceId defines model for BuildInstanceId.
type BuildInstanceId = string

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int

// OrgSlug defines model for OrgSlug.
type OrgSlug = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorEnvelope

// Forbidden defines model for Forbidden.
type Forbidden = ErrorEnvelope

// NotFound defines model for NotFound.
type NotFound = ErrorEnvelope

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorEnvelope

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorEnvelope

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = ErrorEnvelope

// UpdateEmailNotificationsJSONBody defines parameters for UpdateEmailNotifications.
type UpdateEmailNotificationsJSONBody struct {
	Enabled bool `json:"enabled"`
}

// CreateCheckoutSessionJSONBody defines parameters for CreateCheckoutSession.
type CreateCheckoutSessionJSONBody struct {
	Plan      Plan   `json:"plan"`
	ReturnUrl string `json:"return_url"`
}

// CreatePortalSessionJSONBody defines parameters for CreatePortalSession.
type CreatePortalSessionJSONBody struct {
	ReturnUrl string `json:"return_url"`
}

// CreateOrgJSONBody defines parameters for CreateOrg.
type CreateOrgJSONBody struct {
	Name string `json:"name"`
}

// UpdateOrgJSONBody defines parameters for UpdateOrg.
type UpdateOrgJSONBody struct {
	Name string `json:"name"`
}

// ListBuildsParams defines parameters for ListBuilds.
type ListBuildsParams struct {
	// RepositoryId Filter to one repository.
	RepositoryId     *string    `form:"repository_id,omitempty" json:"repository_id,omitempty"`
	Ref              *string    `form:"ref,omitempty" json:"ref,omitempty"`
	CommitSha        *string    `form:"commit_sha,omitempty" json:"commit_sha,omitempty"`
	RegisteredAfter  *time.Time `form:"registered_after,omitempty" json:"registered_after,omitempty"`
	RegisteredBefore *time.Time `form:"registered_before,omitempty" json:"registered_before,omitempty"`

	// Cursor Opaque cursor from a previous page's `next_cursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// RegisterDeclaredBuildParams defines parameters for RegisterDeclaredBuild.
type RegisterDeclaredBuildParams struct {
	// IdempotencyKey Caller-generated, unique per build-registration attempt. The CLI
	// mints one per invocation and never reuses it across distinct
	// builds.
	IdempotencyKey string `json:"Idempotency-Key"`
}

// InviteMemberJSONBody defines parameters for InviteMember.
type InviteMemberJSONBody struct {
	Email string                   `json:"email"`
	Role  InviteMemberJSONBodyRole `json:"role"`
}

// InviteMemberJSONBodyRole defines parameters for InviteMember.
type InviteMemberJSONBodyRole string

// ChangeMemberRoleJSONBody defines parameters for ChangeMemberRole.
type ChangeMemberRoleJSONBody struct {
	Role ChangeMemberRoleJSONBodyRole `json:"role"`
}

// ChangeMemberRoleJSONBodyRole defines parameters for ChangeMemberRole.
type ChangeMemberRoleJSONBodyRole string

// ListReposParams defines parameters for ListRepos.
type ListReposParams struct {
	// Cursor Opaque cursor from a previous page's `next_cursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// UpdateEmailNotificationsJSONRequestBody defines body for UpdateEmailNotifications for application/json ContentType.
type UpdateEmailNotificationsJSONRequestBody UpdateEmailNotificationsJSONBody

// CreateCheckoutSessionJSONRequestBody defines body for CreateCheckoutSession for application/json ContentType.
type CreateCheckoutSessionJSONRequestBody CreateCheckoutSessionJSONBody

// CreatePortalSessionJSONRequestBody defines body for CreatePortalSession for application/json ContentType.
type CreatePortalSessionJSONRequestBody CreatePortalSessionJSONBody

// RegisterBuildJSONRequestBody defines body for RegisterBuild for application/json ContentType.
type RegisterBuildJSONRequestBody = BuildRegistration

// CreateOrgJSONRequestBody defines body for CreateOrg for application/json ContentType.
type CreateOrgJSONRequestBody CreateOrgJSONBody

// UpdateOrgJSONRequestBody defines body for UpdateOrg for application/json ContentType.
type UpdateOrgJSONRequestBody UpdateOrgJSONBody

// RegisterDeclaredBuildJSONRequestBody defines body for RegisterDeclaredBuild for application/json ContentType.
type RegisterDeclaredBuildJSONRequestBody = BuildRegistration

// InviteMemberJSONRequestBody defines body for InviteMember for application/json ContentType.
type InviteMemberJSONRequestBody InviteMemberJSONBody

// ChangeMemberRoleJSONRequestBody defines body for ChangeMemberRole for application/json ContentType.
type ChangeMemberRoleJSONRequestBody ChangeMemberRoleJSONBody

// UpdatePolicyJSONRequestBody defines body for UpdatePolicy for application/json ContentType.
type UpdatePolicyJSONRequestBody = UpdatePolicyRequest

// AuthorizeRepositoryJSONRequestBody defines body for AuthorizeRepository for application/json ContentType.
type AuthorizeRepositoryJSONRequestBody = RepositoryAuthorizeRequest
