// Package protocol provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package protocol

import (
	"time"
)

// Defines values for DriftEventType.
const (
	BuildIdChanged           DriftEventType = "build_id_changed"
	IntegrationHealthChanged DriftEventType = "integration_health_changed"
)

// Valid indicates whether the value is a known member of the DriftEventType enum.
func (e DriftEventType) Valid() bool {
	switch e {
	case BuildIdChanged:
		return true
	case IntegrationHealthChanged:
		return true
	default:
		return false
	}
}

// Defines values for IntegrationHealth.
const (
	Failing           IntegrationHealth = "failing"
	NeverSucceeded    IntegrationHealth = "never_succeeded"
	Ok                IntegrationHealth = "ok"
	Pending           IntegrationHealth = "pending"
	UnsupportedSchema IntegrationHealth = "unsupported_schema"
)

// Valid indicates whether the value is a known member of the IntegrationHealth enum.
func (e IntegrationHealth) Valid() bool {
	switch e {
	case Failing:
		return true
	case NeverSucceeded:
		return true
	case Ok:
		return true
	case Pending:
		return true
	case UnsupportedSchema:
		return true
	default:
		return false
	}
}

// Defines values for Plan.
const (
	Enterprise Plan = "enterprise"
	Free       Plan = "free"
	Paid       Plan = "paid"
)

// Valid indicates whether the value is a known member of the Plan enum.
func (e Plan) Valid() bool {
	switch e {
	case Enterprise:
		return true
	case Free:
		return true
	case Paid:
		return true
	default:
		return false
	}
}

// Defines values for Provider.
const (
	Github Provider = "github"
)

// Valid indicates whether the value is a known member of the Provider enum.
func (e Provider) Valid() bool {
	switch e {
	case Github:
		return true
	default:
		return false
	}
}

// Defines values for TrustDeclarationStatus.
const (
	Confirmed   TrustDeclarationStatus = "confirmed"
	Expired     TrustDeclarationStatus = "expired"
	Invalidated TrustDeclarationStatus = "invalidated"
	Provisional TrustDeclarationStatus = "provisional"
)

// Valid indicates whether the value is a known member of the TrustDeclarationStatus enum.
func (e TrustDeclarationStatus) Valid() bool {
	switch e {
	case Confirmed:
		return true
	case Expired:
		return true
	case Invalidated:
		return true
	case Provisional:
		return true
	default:
		return false
	}
}

// Defines values for Visibility.
const (
	Internal Visibility = "internal"
	Private  Visibility = "private"
	Public   Visibility = "public"
)

// Valid indicates whether the value is a known member of the Visibility enum.
func (e Visibility) Valid() bool {
	switch e {
	case Internal:
		return true
	case Private:
		return true
	case Public:
		return true
	default:
		return false
	}
}

// Build The authenticated disclosure tier — full metadata (spec §2.7).
type Build struct {
	// BuildInstanceId Opaque and server-issued. Content-addressed over the tuple documented on
	// `registerBuild`. Clients MUST treat this as opaque and MUST NOT parse it —
	// the derivation is an implementation detail that may change.
	BuildInstanceId string    `json:"build_instance_id"`
	BuiltAt         time.Time `json:"built_at"`
	CommitAuthor    *string   `json:"commit_author,omitempty"`
	CommitCommitter *string   `json:"commit_committer,omitempty"`
	CommitSha       string    `json:"commit_sha"`

	// Metadata Free-form organization-defined fields (owning team, ticket reference,
	// environment label). Flat string-to-string by design (spec §2.2a): nesting
	// would destabilize the wire type under the compatibility window, hurt
	// queryability, and invite this field to become a blob store.
	//
	// **Always authenticated-tier only.** Customers place arbitrary content here,
	// and the two-tier disclosure model depends on knowing exactly what is public,
	// so these values never appear in the unauthenticated resolution page or its OG
	// tags. There is no per-key public opt-in in v1.
	//
	// Keys beginning `driftmapper.` are reserved and rejected, leaving room to
	// promote custom fields to first-class ones later without collision. The
	// reserved-prefix rule is enforced in server code rather than expressed in the
	// `pattern` below: the natural expression is a negative lookahead, which Go's
	// RE2 engine cannot compile, so encoding it here would produce a schema the
	// server cannot mechanically enforce.
	Metadata *BuildMetadata `json:"metadata,omitempty"`

	// Provider CI provider identity. v1 supports GitHub Actions only; further providers are
	// additive registry entries and appear here as new enum members (spec §4.4).
	// Clients MUST tolerate unknown values in responses.
	//
	// `github` is the issuer registry entry name (`internal/oidc.GitHubActionsProviderName`
	// server-side), not a literal "GitHub Actions" spelling — matches what every
	// `provider`/`claims.Issuer` value on the wire actually contains.
	Provider     *Provider `json:"provider,omitempty"`
	Ref          string    `json:"ref"`
	RegisteredAt time.Time `json:"registered_at"`

	// RepositoryId Provider's stable repository identifier. Internal identity is keyed on
	// this rather than `owner/name`, which changes on rename.
	RepositoryId   string `json:"repository_id"`
	RepositoryName string `json:"repository_name"`

	// RepositoryPath Full `owner/name` path. Authenticated tier only.
	RepositoryPath *string `json:"repository_path,omitempty"`

	// ResolutionUrl Canonical resolution page for this build — the URL written into
	// `build-info.html`. Server-provided so the CLI never constructs it and
	// cannot drift from server routing.
	ResolutionUrl *string `json:"resolution_url,omitempty"`

	// RunAttempt A passthrough OIDC claim value (GitHub's `run_attempt` claim is itself a
	// string), never parsed or compared numerically server-side — only used as
	// one input to the content-address tuple (spec §2.5a). Typed as a string
	// rather than `integer` for that reason.
	RunAttempt   *string `json:"run_attempt,omitempty"`
	RunId        *string `json:"run_id,omitempty"`
	TriggerEvent *string `json:"trigger_event,omitempty"`

	// Visibility Derived from the `repository_visibility` OIDC claim, never client-supplied.
	// This is what gates the Free tier's public-repo allowance (spec §6A), so it is
	// enforced from the signed token with no VCS API call.
	Visibility Visibility `json:"visibility"`
	Workflow   string     `json:"workflow"`
}

// BuildListResponse defines model for BuildListResponse.
type BuildListResponse struct {
	Data struct {
		Items []Build  `json:"items"`
		Page  PageInfo `json:"page"`
	} `json:"data"`
}

// BuildMetadata Free-form organization-defined fields (owning team, ticket reference,
// environment label). Flat string-to-string by design (spec §2.2a): nesting
// would destabilize the wire type under the compatibility window, hurt
// queryability, and invite this field to become a blob store.
//
// **Always authenticated-tier only.** Customers place arbitrary content here,
// and the two-tier disclosure model depends on knowing exactly what is public,
// so these values never appear in the unauthenticated resolution page or its OG
// tags. There is no per-key public opt-in in v1.
//
// Keys beginning `driftmapper.` are reserved and rejected, leaving room to
// promote custom fields to first-class ones later without collision. The
// reserved-prefix rule is enforced in server code rather than expressed in the
// `pattern` below: the natural expression is a negative lookahead, which Go's
// RE2 engine cannot compile, so encoding it here would produce a schema the
// server cannot mechanically enforce.
type BuildMetadata map[string]string

// BuildPublic The unauthenticated disclosure tier (spec §2.7). This is exactly what link
// unfurlers and logged-out visitors see on the resolution page: enough to make
// a preview useful and confirm the link is a real Driftmapper build link,
// and nothing more.
//
// Deliberately excludes committer, author, internal repository path, and all
// custom metadata. This tier matches the disclosure boundary teams already have
// with a plain public build-info file, so nothing that is public today becomes
// private and nothing private today becomes public.
type BuildPublic struct {
	BuildInstanceId string    `json:"build_instance_id"`
	BuiltAt         time.Time `json:"built_at"`

	// RepositoryName Short repository name only — never the full internal path.
	RepositoryName string `json:"repository_name"`
}

// BuildRegistration Only fields the OIDC token cannot attest to. Everything derivable from
// verified claims is server-derived and rejected here (spec §2.2a).
type BuildRegistration struct {
	BuiltAt time.Time `json:"built_at"`

	// CommitAuthor Normalized by the CLI from provider-specific build context.
	CommitAuthor    *string `json:"commit_author,omitempty"`
	CommitCommitter *string `json:"commit_committer,omitempty"`
	CommitSha       string  `json:"commit_sha"`

	// Metadata Free-form organization-defined fields (owning team, ticket reference,
	// environment label). Flat string-to-string by design (spec §2.2a): nesting
	// would destabilize the wire type under the compatibility window, hurt
	// queryability, and invite this field to become a blob store.
	//
	// **Always authenticated-tier only.** Customers place arbitrary content here,
	// and the two-tier disclosure model depends on knowing exactly what is public,
	// so these values never appear in the unauthenticated resolution page or its OG
	// tags. There is no per-key public opt-in in v1.
	//
	// Keys beginning `driftmapper.` are reserved and rejected, leaving room to
	// promote custom fields to first-class ones later without collision. The
	// reserved-prefix rule is enforced in server code rather than expressed in the
	// `pattern` below: the natural expression is a negative lookahead, which Go's
	// RE2 engine cannot compile, so encoding it here would produce a schema the
	// server cannot mechanically enforce.
	Metadata *BuildMetadata `json:"metadata,omitempty"`

	// TriggerEvent Normalized trigger, e.g. `push`, `pull_request`, `manual`.
	TriggerEvent *string `json:"trigger_event,omitempty"`
}

// BuildResponse defines model for BuildResponse.
type BuildResponse struct {
	// Data The authenticated disclosure tier — full metadata (spec §2.7).
	Data Build `json:"data"`
}

// ClaimMismatchDetails `error.details` shape when `error.code` is `claim_mismatch`: a signature-
// valid token whose claims did not match any trust declaration.
//
// The mismatched field is named explicitly rather than returning a generic
// authentication failure. This is the single most likely point of first-run
// abandonment — a case-sensitive workflow filename mismatch is a well-
// documented source of setup friction in comparable systems (spec §4.5) —
// and a specific error is cheap to produce and turns a dead end into a
// one-line fix.
type ClaimMismatchDetails struct {
	// Actual Value from the verified token. Safe to echo: the caller demonstrably
	// already holds this token.
	Actual string `json:"actual"`

	// Expected Value from the trust declaration.
	Expected string `json:"expected"`

	// MismatchedClaim e.g. `workflow`, `repository`, `ref`, `environment`.
	MismatchedClaim string `json:"mismatched_claim"`
}

// CreateTrustDeclarationRequest defines model for CreateTrustDeclarationRequest.
type CreateTrustDeclarationRequest struct {
	// Environment Optional. Omitted/empty matches any environment.
	Environment *string `json:"environment,omitempty"`

	// Provider CI provider identity. v1 supports GitHub Actions only; further providers are
	// additive registry entries and appear here as new enum members (spec §4.4).
	// Clients MUST tolerate unknown values in responses.
	//
	// `github` is the issuer registry entry name (`internal/oidc.GitHubActionsProviderName`
	// server-side), not a literal "GitHub Actions" spelling — matches what every
	// `provider`/`claims.Issuer` value on the wire actually contains.
	Provider Provider `json:"provider"`

	// Ref Optional. Omitted/empty matches any ref.
	Ref *string `json:"ref,omitempty"`

	// Repository `owner/name`. Unverified until confirmation.
	Repository string `json:"repository"`

	// Workflow Filename including extension (e.g. `ci.yml`), matched against the bare
	// filename extracted from a `workflow_ref`-shaped claim — never the raw
	// claim value. Required: an empty/omitted `workflow` would otherwise match
	// any workflow in the repository, which is not this operation's default.
	Workflow string `json:"workflow"`
}

// DriftEvent defines model for DriftEvent.
type DriftEvent struct {
	CurrentBuildInstanceId *string `json:"current_build_instance_id,omitempty"`

	// CurrentHealth Whether Driftmapper can do its job at this URL — not whether the site is up.
	//
	// - `pending` — registered, not yet successfully polled.
	// - `ok` — last poll parsed a build ID.
	// - `never_succeeded` — has never once succeeded. Surfaced immediately, since
	//   this almost always means a setup error, not an outage.
	// - `failing` — previously succeeded, now failing past the sustained-failure
	//   threshold.
	// - `unsupported_schema` — the file was fetched and parsed, but its
	//   `driftmapper:schema-version` is one this server does not understand. Held
	//   distinct from `failing` on purpose: it is neither drift nor a fetch error,
	//   and the remedy is different (upgrade the server or the CLI, not fix the
	//   deployment).
	CurrentHealth  *IntegrationHealth `json:"current_health,omitempty"`
	DriftEventId   string             `json:"drift_event_id"`
	MonitoredUrlId string             `json:"monitored_url_id"`
	ObservedAt     time.Time          `json:"observed_at"`

	// PreviousBuildInstanceId Null for the first observation at a URL.
	PreviousBuildInstanceId *string `json:"previous_build_instance_id,omitempty"`

	// PreviousHealth Whether Driftmapper can do its job at this URL — not whether the site is up.
	//
	// - `pending` — registered, not yet successfully polled.
	// - `ok` — last poll parsed a build ID.
	// - `never_succeeded` — has never once succeeded. Surfaced immediately, since
	//   this almost always means a setup error, not an outage.
	// - `failing` — previously succeeded, now failing past the sustained-failure
	//   threshold.
	// - `unsupported_schema` — the file was fetched and parsed, but its
	//   `driftmapper:schema-version` is one this server does not understand. Held
	//   distinct from `failing` on purpose: it is neither drift nor a fetch error,
	//   and the remedy is different (upgrade the server or the CLI, not fix the
	//   deployment).
	PreviousHealth *IntegrationHealth `json:"previous_health,omitempty"`
	RepositoryId   string             `json:"repository_id"`
	Type           DriftEventType     `json:"type"`
}

// DriftEventListResponse defines model for DriftEventListResponse.
type DriftEventListResponse struct {
	Data struct {
		Items []DriftEvent `json:"items"`
		Page  PageInfo     `json:"page"`
	} `json:"data"`
}

// DriftEventType defines model for DriftEventType.
type DriftEventType string

// Error The `error` half of the response envelope (see "Response envelope" above).
// Not RFC 9457 — a from-scratch shape matching what every `cmd/api` route
// actually emits (`internal/api/respond.go`'s `errorBody`).
type Error struct {
	// Code Stable, machine-readable identity of the error. Clients branch on this,
	// never on `message`, which may be reworded without a version bump.
	// Examples: `validation`, `unauthorized`, `forbidden`, `not_found`,
	// `unknown_field`, `claim_mismatch`, `no_trust_declaration`.
	Code string `json:"code"`

	// Details Structured, error-specific fields a client can act on programmatically.
	// Present only for errors that have them (currently `claim_mismatch` —
	// see `ClaimMismatchDetails` — and, once slot enforcement lands,
	// `plan_limit` — see `PlanLimitDetails`); absent otherwise.
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Human-readable, safe to display directly.
	Message string `json:"message"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	// Error The `error` half of the response envelope (see "Response envelope" above).
	// Not RFC 9457 — a from-scratch shape matching what every `cmd/api` route
	// actually emits (`internal/api/respond.go`'s `errorBody`).
	Error Error `json:"error"`
}

// IntegrationHealth Whether Driftmapper can do its job at this URL — not whether the site is up.
//
//   - `pending` — registered, not yet successfully polled.
//   - `ok` — last poll parsed a build ID.
//   - `never_succeeded` — has never once succeeded. Surfaced immediately, since
//     this almost always means a setup error, not an outage.
//   - `failing` — previously succeeded, now failing past the sustained-failure
//     threshold.
//   - `unsupported_schema` — the file was fetched and parsed, but its
//     `driftmapper:schema-version` is one this server does not understand. Held
//     distinct from `failing` on purpose: it is neither drift nor a fetch error,
//     and the remedy is different (upgrade the server or the CLI, not fix the
//     deployment).
type IntegrationHealth string

// MonitoredUrl defines model for MonitoredUrl.
type MonitoredUrl struct {
	CreatedAt time.Time `json:"created_at"`

	// Health Whether Driftmapper can do its job at this URL — not whether the site is up.
	//
	// - `pending` — registered, not yet successfully polled.
	// - `ok` — last poll parsed a build ID.
	// - `never_succeeded` — has never once succeeded. Surfaced immediately, since
	//   this almost always means a setup error, not an outage.
	// - `failing` — previously succeeded, now failing past the sustained-failure
	//   threshold.
	// - `unsupported_schema` — the file was fetched and parsed, but its
	//   `driftmapper:schema-version` is one this server does not understand. Held
	//   distinct from `failing` on purpose: it is neither drift nor a fetch error,
	//   and the remedy is different (upgrade the server or the CLI, not fix the
	//   deployment).
	Health IntegrationHealth `json:"health"`
	Label  *string           `json:"label,omitempty"`

	// LastChangeObservedAt When the build ID at this URL last changed — not when it was last
	// polled. Poll timestamps are not stored (spec §2.6).
	LastChangeObservedAt *time.Time `json:"last_change_observed_at,omitempty"`

	// LastSeenBuildInstanceId Most recent build-instance ID parsed at this URL. Null until the first
	// successful poll.
	LastSeenBuildInstanceId *string `json:"last_seen_build_instance_id,omitempty"`
	MonitoredUrlId          string  `json:"monitored_url_id"`
	RepositoryId            string  `json:"repository_id"`
	Url                     string  `json:"url"`
}

// MonitoredUrlListResponse defines model for MonitoredUrlListResponse.
type MonitoredUrlListResponse struct {
	Data struct {
		Items []MonitoredUrl `json:"items"`
		Page  PageInfo       `json:"page"`
	} `json:"data"`
}

// MonitoredUrlResponse defines model for MonitoredUrlResponse.
type MonitoredUrlResponse struct {
	Data MonitoredUrl `json:"data"`
}

// Organization defines model for Organization.
type Organization struct {
	Name           string `json:"name"`
	OrganizationId string `json:"organization_id"`
	Plan           Plan   `json:"plan"`

	// SlotsIncluded Null on Enterprise, which is not gated on repository count.
	SlotsIncluded *int `json:"slots_included,omitempty"`

	// SlotsUsed Private repositories consuming a plan slot.
	SlotsUsed   int   `json:"slots_used"`
	SsoEnforced *bool `json:"sso_enforced,omitempty"`
}

// OrganizationResponse defines model for OrganizationResponse.
type OrganizationResponse struct {
	Data Organization `json:"data"`
}

// PageInfo defines model for PageInfo.
type PageInfo struct {
	HasMore bool `json:"has_more"`

	// NextCursor Present only when `has_more` is true.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// Plan defines model for Plan.
type Plan string

// PlanLimitDetails `error.details` shape when `error.code` is `plan_limit`: confirming this
// repository would exceed the plan's slot allowance. Returned at confirmation
// time rather than declaration time, so an unconfirmed declaration never
// consumes a slot (spec §4.5). Not yet emitted by the server — plan-slot
// enforcement lands in DRFT-22 — documented here as the shape it will use.
type PlanLimitDetails struct {
	SlotsIncluded int     `json:"slots_included"`
	SlotsUsed     int     `json:"slots_used"`
	UpgradeUrl    *string `json:"upgrade_url,omitempty"`
}

// Provider CI provider identity. v1 supports GitHub Actions only; further providers are
// additive registry entries and appear here as new enum members (spec §4.4).
// Clients MUST tolerate unknown values in responses.
//
// `github` is the issuer registry entry name (`internal/oidc.GitHubActionsProviderName`
// server-side), not a literal "GitHub Actions" spelling — matches what every
// `provider`/`claims.Issuer` value on the wire actually contains.
type Provider string

// Repository defines model for Repository.
type Repository struct {
	// ConsumesPlanSlot False for public repositories on the Free tier, which are unmetered
	// (spec §6A).
	ConsumesPlanSlot      *bool     `json:"consumes_plan_slot,omitempty"`
	LatestBuildInstanceId *string   `json:"latest_build_instance_id,omitempty"`
	LinkedAt              time.Time `json:"linked_at"`

	// Path `owner/name` at time of last build.
	Path string `json:"path"`

	// Provider CI provider identity. v1 supports GitHub Actions only; further providers are
	// additive registry entries and appear here as new enum members (spec §4.4).
	// Clients MUST tolerate unknown values in responses.
	//
	// `github` is the issuer registry entry name (`internal/oidc.GitHubActionsProviderName`
	// server-side), not a literal "GitHub Actions" spelling — matches what every
	// `provider`/`claims.Issuer` value on the wire actually contains.
	Provider     Provider `json:"provider"`
	RepositoryId string   `json:"repository_id"`

	// Visibility Derived from the `repository_visibility` OIDC claim, never client-supplied.
	// This is what gates the Free tier's public-repo allowance (spec §6A), so it is
	// enforced from the signed token with no VCS API call.
	Visibility Visibility `json:"visibility"`
}

// RepositoryListResponse defines model for RepositoryListResponse.
type RepositoryListResponse struct {
	Data struct {
		Items []Repository `json:"items"`
		Page  PageInfo     `json:"page"`
	} `json:"data"`
}

// TrustDeclaration defines model for TrustDeclaration.
type TrustDeclaration struct {
	ConfirmedAt *time.Time `json:"confirmed_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`

	// Environment Absent means "any environment accepted."
	Environment *string `json:"environment,omitempty"`

	// ExpiresAt Applies while `provisional`.
	ExpiresAt time.Time `json:"expires_at"`
	Id        int64     `json:"id"`

	// Provider CI provider identity. v1 supports GitHub Actions only; further providers are
	// additive registry entries and appear here as new enum members (spec §4.4).
	// Clients MUST tolerate unknown values in responses.
	//
	// `github` is the issuer registry entry name (`internal/oidc.GitHubActionsProviderName`
	// server-side), not a literal "GitHub Actions" spelling — matches what every
	// `provider`/`claims.Issuer` value on the wire actually contains.
	Provider Provider `json:"provider"`

	// Ref Absent means "any ref accepted."
	Ref *string `json:"ref,omitempty"`

	// Repository `owner/name`, as declared. Unverified until confirmation.
	Repository string `json:"repository"`

	// RepositoryId Populated on confirmation. This is Driftmapper's internal repository id
	// (`repositories.id`), NOT the provider's stable repository id returned as
	// `Repository.repository_id` / `Build.repository_id` elsewhere in this API
	// — those two identifier spaces are not directly comparable today. Worth
	// resolving before a client tries to correlate a confirmed declaration with
	// its `/v1/repos` entry.
	RepositoryId *int64 `json:"repository_id,omitempty"`

	// Status - `provisional` — created, unconfirmed, grants nothing, consumes no slot.
	// - `confirmed` — a matching valid token was received; repository is linked and
	//   a plan slot is consumed.
	// - `invalidated` — another organization confirmed this repository first.
	// - `expired` — never confirmed within the expiry window.
	Status   TrustDeclarationStatus `json:"status"`
	Workflow string                 `json:"workflow"`
}

// TrustDeclarationListResponse defines model for TrustDeclarationListResponse.
type TrustDeclarationListResponse struct {
	Data []TrustDeclaration `json:"data"`
}

// TrustDeclarationResponse defines model for TrustDeclarationResponse.
type TrustDeclarationResponse struct {
	Data TrustDeclaration `json:"data"`
}

// TrustDeclarationStatus - `provisional` — created, unconfirmed, grants nothing, consumes no slot.
//   - `confirmed` — a matching valid token was received; repository is linked and
//     a plan slot is consumed.
//   - `invalidated` — another organization confirmed this repository first.
//   - `expired` — never confirmed within the expiry window.
type TrustDeclarationStatus string

// Visibility Derived from the `repository_visibility` OIDC claim, never client-supplied.
// This is what gates the Free tier's public-repo allowance (spec §6A), so it is
// enforced from the signed token with no VCS API call.
type Visibility string

// BuildInstanceId defines model for BuildInstanceId.
type BuildInstanceId = string

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int

// OrgSlug defines model for OrgSlug.
type OrgSlug = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorEnvelope

// Forbidden defines model for Forbidden.
type Forbidden = ErrorEnvelope

// NotFound defines model for NotFound.
type NotFound = ErrorEnvelope

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorEnvelope

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = ErrorEnvelope

// CreateCheckoutSessionJSONBody defines parameters for CreateCheckoutSession.
type CreateCheckoutSessionJSONBody struct {
	Plan      Plan   `json:"plan"`
	ReturnUrl string `json:"return_url"`
}

// CreatePortalSessionJSONBody defines parameters for CreatePortalSession.
type CreatePortalSessionJSONBody struct {
	ReturnUrl string `json:"return_url"`
}

// ListBuildsParams defines parameters for ListBuilds.
type ListBuildsParams struct {
	// RepositoryId Filter to one repository.
	RepositoryId    *string    `form:"repository_id,omitempty" json:"repository_id,omitempty"`
	Ref             *string    `form:"ref,omitempty" json:"ref,omitempty"`
	CommitSha       *string    `form:"commit_sha,omitempty" json:"commit_sha,omitempty"`
	RegisteredAfter *time.Time `form:"registered_after,omitempty" json:"registered_after,omitempty"`

	// Cursor Opaque cursor from a previous page's `next_cursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListDriftEventsParams defines parameters for ListDriftEvents.
type ListDriftEventsParams struct {
	RepositoryId   *string         `form:"repository_id,omitempty" json:"repository_id,omitempty"`
	MonitoredUrlId *string         `form:"monitored_url_id,omitempty" json:"monitored_url_id,omitempty"`
	Type           *DriftEventType `form:"type,omitempty" json:"type,omitempty"`
	ObservedAfter  *time.Time      `form:"observed_after,omitempty" json:"observed_after,omitempty"`

	// Cursor Opaque cursor from a previous page's `next_cursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListMonitoredUrlsParams defines parameters for ListMonitoredUrls.
type ListMonitoredUrlsParams struct {
	RepositoryId *string `form:"repository_id,omitempty" json:"repository_id,omitempty"`

	// Cursor Opaque cursor from a previous page's `next_cursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateMonitoredUrlJSONBody defines parameters for CreateMonitoredUrl.
type CreateMonitoredUrlJSONBody struct {
	// Label Human label, e.g. "production" or "staging".
	Label *string `json:"label,omitempty"`

	// RepositoryId Must reference a confirmed repository.
	RepositoryId string `json:"repository_id"`

	// Url Absolute URL of the deployed `build-info.html`. HTTPS only.
	Url string `json:"url"`
}

// ListReposParams defines parameters for ListRepos.
type ListReposParams struct {
	// Cursor Opaque cursor from a previous page's `next_cursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateCheckoutSessionJSONRequestBody defines body for CreateCheckoutSession for application/json ContentType.
type CreateCheckoutSessionJSONRequestBody CreateCheckoutSessionJSONBody

// CreatePortalSessionJSONRequestBody defines body for CreatePortalSession for application/json ContentType.
type CreatePortalSessionJSONRequestBody CreatePortalSessionJSONBody

// RegisterBuildJSONRequestBody defines body for RegisterBuild for application/json ContentType.
type RegisterBuildJSONRequestBody = BuildRegistration

// CreateMonitoredUrlJSONRequestBody defines body for CreateMonitoredUrl for application/json ContentType.
type CreateMonitoredUrlJSONRequestBody CreateMonitoredUrlJSONBody

// CreateTrustDeclarationJSONRequestBody defines body for CreateTrustDeclaration for application/json ContentType.
type CreateTrustDeclarationJSONRequestBody = CreateTrustDeclarationRequest
